In [1]:
import json

In [53]:
import json

file_path = '../datasets/cath-4.2/chain_set_splits.json'

with open(file_path, 'r') as file:
    data = json.load(file)



In [3]:
print(data.keys())  # For example, print the top-level keys

dict_keys(['test', 'cath_nodes', 'train', 'validation'])


In [ ]:
pdbs_to_check = [
    "1es0.A",
    "1jpl.A",
    "1k47.A",
    "1nlq.E",
    "1nri.A",
    "1pc3.A",
    "1wte.A",
    "1wte.B",
    "2atc.A",
    "2atc.B",
    
]

train_val_problems = []
test_problems = []

for pdb in pdbs_to_check:
    if pdb in data['test']:
        test_problems.append(pdb)
    else:
        train_val_problems.append(pdb)

train_val_problems

['1es0.A',
 '1jpl.A',
 '1k47.A',
 '1nlq.E',
 '1nri.A',
 '1pc3.A',
 '2atc.A',
 '2atc.B']

In [4]:
len(data['train']), len(data['validation']), len(data['test']), len(data['cath_nodes'])

(18024, 608, 1120, 21573)

In [6]:
data["validation"]

['2e6i.A',
 '2mh3.A',
 '3gn4.E',
 '2qg3.A',
 '3abd.B',
 '1z8s.A',
 '5t5d.A',
 '1f7e.A',
 '2lg7.A',
 '1h2s.A',
 '4bdx.A',
 '1yf9.A',
 '2p2e.A',
 '1lmm.A',
 '1cel.A',
 '2kil.A',
 '1c52.A',
 '2gmy.D',
 '1go4.A',
 '4atk.B',
 '1nyn.A',
 '3o2u.A',
 '2c6u.A',
 '2ctt.A',
 '2c8s.A',
 '3hxi.A',
 '2l4d.A',
 '3o7p.A',
 '1erz.A',
 '1e29.A',
 '5b2n.A',
 '3sqf.A',
 '3bxj.A',
 '3bxj.B',
 '2wg3.D',
 '1fmb.A',
 '1xkr.A',
 '2z73.B',
 '4ww7.B',
 '2lez.A',
 '1gz2.A',
 '4ds7.E',
 '4mit.G',
 '1i1r.B',
 '2je2.A',
 '2hp7.A',
 '1ahq.A',
 '1x4r.A',
 '5d0y.A',
 '1ukl.C',
 '2qgo.A',
 '1aih.A',
 '1qgj.A',
 '1k6d.B',
 '4gkf.A',
 '1poi.B',
 '1lmj.A',
 '1jzn.A',
 '3e0s.B',
 '1o8r.A',
 '1m70.A',
 '1dym.A',
 '4mb8.D',
 '3lnb.A',
 '3bdw.B',
 '3ddl.B',
 '3lvy.A',
 '1cee.B',
 '2afp.A',
 '3emi.A',
 '1e8o.A',
 '1ukx.A',
 '1e8o.D',
 '2gov.A',
 '4ex8.A',
 '1m3e.A',
 '1m4j.A',
 '4b6u.A',
 '1dx5.I',
 '5al9.A',
 '3p8k.A',
 '4q65.A',
 '2pva.A',
 '1vpu.A',
 '3ndh.A',
 '1b08.C',
 '1bow.A',
 '1jli.A',
 '1x0g.A',
 '1sqp.F',
 '1m4r.B',

In [42]:
import pickle
with open('../datasets/cath-4.2/chain_set_map_with_b_factors.pkl', 'rb') as file:
    data_pdb = pickle.load(file)

In [58]:
pdb_id = '1a2f.A'
sample = data_pdb[pdb_id]
sample['seq'], sample['b_factors']

('LVHVASVEKGRSYEDFQKVYNAIALKLREDDEYDNYIGYGPVLVRLAWHISGTWDKHDNTGGSYGGTYRFKKEFNDPSNAGLQNGFKFLEPIHKEFPWISSGDLFSLGGVTAVQEMQGPKIPWRCGRVDTPEDTTPDNGRLPDADKDAGYVRTFFQRLNMNDREVVALKGAHALGKTHLKNSGYEGPWGAANNVFTNEFYLNLLNEDWKLEKNDANNEQWDSKSGYMMLPTDYSLIQDPKYLSIVKEYANDQDKFFKDFSKAFEKLLENGITFPKDAPSPFIFKTLEEQGL',
 array([21.5325, 18.38  , 16.645 , 14.2225, 14.3475, 20.275 , 17.7275,
        16.5075, 17.475 , 18.0825, 16.445 , 19.76  , 14.45  , 16.2575,
        17.36  , 13.585 , 13.0525, 15.9875, 15.915 , 13.7975, 19.8625,
        18.945 , 21.5525, 19.6925, 17.87  , 15.2075, 16.0125, 17.98  ,
        17.21  , 15.51  , 15.82  , 18.56  , 17.585 , 21.2   , 15.515 ,
        16.585 , 22.7475, 24.415 , 28.1875, 34.8825, 33.055 , 26.725 ,
        24.435 , 26.0275, 21.6625, 23.2725, 24.67  , 22.1675, 19.365 ,
        18.2925, 18.83  , 20.155 , 21.95  , 25.2525, 20.09  , 21.2425,
        17.8625, 19.9125, 18.1825, 18.5975, 18.485 , 19.22  , 21.28  ,
        21.7525, 19.29  , 19.45  , 26.0875, 17.5675, 16.475 , 18.

In [52]:
pdb_id = '2atc.A'
sample = data_pdb[pdb_id]
sample['seq'], sample['b_factors'], len(sample['seq'])

('ANPLYQSHIISINDLSRDDLNLVLATAAKLKANPQPELLKHKVIASCFFEASTRTRLSFQTSMHRLGASVVGFSDSANTSLGKKGQTLANTISVISTYVDAIVMRHPQEGAARLATEFSGNVPVLNAGDGSNQHPTQTLLDLFTIQQTEGRLNNLHVAMVGDLKYGRTVHSLTQALAKFDGNRFYFIAPDALAMPEYILDMLDEKGIAWSLHSSIEEVMTRVQKERLDPSEYABVKAQFLVRANSLGGLHNAKMNAKVLHPLPRVDEIATDVDKTPHAWYFQQAGNGIFARQALLALVLNRDLVL',
 array([50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
        50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
        50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
        50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
        50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
        50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
        50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
        50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
        50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
        50., 50., 50., 50., 50., 

In [18]:
data['12as.A']['coords'].keys()

dict_keys(['N', 'CA', 'C', 'O'])

In [13]:
pdb_id = '4bdx.A'  
data_pdb[pdb_id]['coords'], data_pdb[pdb_id]["seq"]

({'N': array([[        nan,         nan,         nan],
         [ 4.5970e+00, -4.5900e+00, -3.8792e+01],
         [ 4.2700e+00, -4.2360e+00, -3.6155e+01],
         [ 4.6220e+00, -2.8120e+00, -3.2871e+01],
         [ 7.1130e+00, -2.2750e+00, -3.0339e+01],
         [ 6.9990e+00, -2.8430e+00, -2.6854e+01],
         [ 8.3960e+00, -1.1420e+00, -2.4130e+01],
         [ 8.7560e+00, -1.7960e+00, -2.0853e+01],
         [ 1.0206e+01, -3.9400e-01, -1.8906e+01],
         [ 1.0143e+01,  2.1890e+00, -1.9573e+01],
         [ 7.5710e+00,  2.7110e+00, -1.9971e+01],
         [ 6.5950e+00,  2.8560e+00, -2.2613e+01],
         [ 5.8440e+00,  2.6360e+00, -2.6105e+01],
         [ 7.6820e+00,  1.5900e+00, -2.8941e+01],
         [ 8.5000e+00,  2.2670e+00, -3.2342e+01],
         [ 9.1410e+00,  1.6600e-01, -3.5195e+01],
         [ 1.2549e+01, -3.1100e-01, -3.5752e+01],
         [ 1.3341e+01,  1.7760e+00, -3.4087e+01],
         [ 1.5492e+01,  2.8750e+00, -3.1402e+01],
         [ 1.6649e+01,  2.3180e+00, -2.8098e+

In [2]:
pdb_id = '2qg3.A'  
data_pdb[pdb_id]['coords'], data_pdb[pdb_id]["seq"]

({'N': array([[        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [ 1.6570e+01,  1.5460e+00,  9.5249e+01],
         [ 1.5341e+01,  2.6690e+00,  9.2860e+01],
         [ 1.6990e+01,  4.9250e+00,  9.2227e+01],
         [ 1.9439e+01,  3.7540e+00,  9.1625e+01],
         [ 1.8691e+01,  2.1210e+00,  8.9497e+01],
         [ 1.7819e+01,  4.1340e+00,  8.7647e+01],
         [ 2.0303e+01,  5.4580e+00,  8.7316e+

In [ ]:
import pickle

with open('../datasets/cath-4.2/chain_set_map_with_b_factors_dssp.pkl', 'rb') as file:
    data_dssp = pickle.load(file)

In [37]:
id = '12as.A'
entry = data_dssp[id]

In [39]:
len(entry['dssp']), len(entry['seq']), len(entry['b_factors']), len(entry['coords']['N'])

(330, 330, 330, 330)

In [41]:
for i, dssp in enumerate(entry['dssp']):
    print(f"Position {i}: DSSP = {dssp}, Seq = {entry['seq'][i]}, B-Factor = {entry['b_factors'][i]}, Coord N = {entry['coords']['N'][i]}")

Position 0: DSSP = X, Seq = M, B-Factor = 22.59000015258789, Coord N = [nan nan nan]
Position 1: DSSP = X, Seq = K, B-Factor = 7.34250020980835, Coord N = [nan nan nan]
Position 2: DSSP = X, Seq = T, B-Factor = 13.137499809265137, Coord N = [nan nan nan]
Position 3: DSSP = -, Seq = A, B-Factor = 16.8075008392334, Coord N = [11.751 37.846 29.016]
Position 4: DSSP = H, Seq = Y, B-Factor = 14.404999732971191, Coord N = [14.235 39.531 26.906]
Position 5: DSSP = H, Seq = I, B-Factor = 21.93000030517578, Coord N = [16.789 39.63  28.369]
Position 6: DSSP = H, Seq = A, B-Factor = 21.149999618530273, Coord N = [16.368 37.519 30.261]
Position 7: DSSP = H, Seq = K, B-Factor = 19.927499771118164, Coord N = [15.825 35.211 28.535]
Position 8: DSSP = H, Seq = Q, B-Factor = 2.680000066757202, Coord N = [18.356 35.312 27.173]
Position 9: DSSP = H, Seq = R, B-Factor = 11.8125, Coord N = [20.058 34.382 29.069]
Position 10: DSSP = H, Seq = Q, B-Factor = 5.03249979019165, Coord N = [19.058 31.934 29.727]
P

In [6]:
import torch
import numpy as np

In [11]:
for pdb_id in data['validation']:
    coords, seq = data_pdb[pdb_id]['coords'], data_pdb[pdb_id]["seq"]
    len_seq = len(seq)
    if len_seq < 200 or len_seq > 300:
        continue
    # ensure there is no NaN in coords
    if any(np.isnan(coords[k]).any() for k in coords):
        continue
    # if any unknown amino acids in seq
    if any(aa not in 'ACDEFGHIKLMNPQRSTVWY' for aa in seq):
        continue
    print(f"{pdb_id}: {len_seq} residues")

1h2s.A: 225 residues
1qgj.A: 300 residues
1poi.B: 260 residues
4b6u.A: 207 residues
1j31.A: 262 residues
1nmo.A: 247 residues
2fyw.A: 267 residues
1cpo.A: 299 residues
4hyn.A: 202 residues
2yyb.A: 242 residues
1a2f.A: 291 residues
1ap8.A: 213 residues
1dmu.A: 299 residues
1h32.A: 261 residues
1bek.A: 291 residues
1nmp.A: 247 residues
2iie.A: 204 residues
1b96.A: 244 residues
1h31.A: 261 residues


In [6]:
data_pdb["1h2s.A"]['coords']['N'][42]

array([24.419,  7.073, 17.332], dtype=float32)

In [7]:
for pdb_id in data['validation']:
    coords, seq = data_pdb[pdb_id]['coords'], data_pdb[pdb_id]["seq"]
    len_seq = len(seq)
    if len_seq < 100 or len_seq > 200:
        continue
    # ensure there is no NaN in coords
    if any(np.isnan(coords[k]).any() for k in coords):
        continue
    # if any unknown amino acids in seq
    if any(aa not in 'ACDEFGHIKLMNPQRSTVWY' for aa in seq):
        continue
    print(f"{pdb_id}: {len_seq} residues")

1z8s.A: 146 residues
2lg7.A: 129 residues
2kil.A: 181 residues
1c52.A: 131 residues
3o2u.A: 190 residues
2c6u.A: 122 residues
2ctt.A: 104 residues
1e29.A: 135 residues
1fmb.A: 104 residues
1aih.A: 170 residues
1jzn.A: 135 residues
1m70.A: 190 residues
1ukx.A: 137 residues
1dx5.I: 118 residues
1jli.A: 112 residues
1c3a.A: 135 residues
3cx5.G: 126 residues
2daw.A: 154 residues
1v6f.A: 151 residues
1irl.A: 133 residues
2day.A: 128 residues
2d8b.A: 166 residues
2lzn.A: 143 residues
1j3e.A: 115 residues
3tip.A: 132 residues
1bbn.A: 133 residues
2yz0.A: 138 residues
2bo5.A: 120 residues
1fcd.C: 174 residues
1rjh.A: 118 residues
2lxx.A: 152 residues
2kcu.A: 166 residues
1wu3.I: 161 residues
1dw0.A: 112 residues
1dv8.A: 128 residues
1xko.B: 159 residues
2mp4.A: 165 residues
3liy.A: 116 residues
3zqs.A: 186 residues
1sbx.A: 106 residues
2mv2.A: 148 residues
1a7m.A: 180 residues
2m74.A: 136 residues
1jbi.A: 100 residues
2dk6.A: 102 residues
2ebk.A: 128 residues
1ujr.A: 110 residues
3m3g.A: 120 r

In [8]:
import numpy as np

In [9]:
for pdb_id in data['validation']:
    coords, seq = data_pdb[pdb_id]['coords'], data_pdb[pdb_id]["seq"]
    len_seq = len(seq)
    if len_seq < 400:
        continue
    # ensure there is no NaN in coords
    if any(np.isnan(coords[k]).any() for k in coords):
        continue
    # if any unknown amino acids in seq
    if any(aa not in 'ACDEFGHIKLMNPQRSTVWY' for aa in seq):
        continue
    print(f"{pdb_id}: {len_seq} residues")

1cel.A: 434 residues
3hhw.K: 421 residues
3vla.A: 413 residues
2cfq.A: 417 residues


In [10]:
for pdb_id in data['validation']:
    coords, seq = data_pdb[pdb_id]['coords'], data_pdb[pdb_id]["seq"]
    len_seq = len(seq)
    if len_seq < 400:
        continue
    # ensure there is no NaN in coords
    if not any(np.isnan(coords[k]).any() for k in coords):
        continue
    # if any unknown amino acids in seq
    if any(aa not in 'ACDEFGHIKLMNPQRSTVWY' for aa in seq):
        continue
    print(f"{pdb_id}: {len_seq} residues")

3o7p.A: 438 residues
3bxj.A: 483 residues
3bxj.B: 483 residues
2wg3.D: 463 residues
2z73.B: 448 residues
1dym.A: 402 residues
1m3e.A: 481 residues
4q65.A: 493 residues
3gia.A: 444 residues
4lds.A: 446 residues
4pph.A: 417 residues
1kpl.A: 473 residues
3o7q.A: 438 residues
4iu9.A: 468 residues
2gtt.C: 450 residues
2gtt.J: 450 residues
2gic.D: 422 residues
4mbs.A: 414 residues
1pw4.A: 451 residues
4dwp.A: 462 residues
4d2c.A: 491 residues
4iu8.A: 468 residues
4qiq.A: 479 residues
2iqg.A: 406 residues
4gc0.A: 491 residues
2vhh.A: 405 residues
4kp1.A: 445 residues
3aup.D: 403 residues


In [18]:
coords = data_pdb['4q65.A']['coords']['CA']
# count the number of rows with any nan value
missing = 0
for k in range(len(coords)):
    if np.isnan(coords[k]).any():
        missing += 1
missing

56

In [6]:
# Find the entry with the longest sequence in 'test'
max_test = max(data['test'], key=lambda pdb_id: len(data_pdb[pdb_id]['seq']))
max_test_len = len(data_pdb[max_test]['seq'])

# Find the entry with the longest sequence in 'validation'
max_val = max(data['validation'], key=lambda pdb_id: len(data_pdb[pdb_id]['seq']))
max_val_len = len(data_pdb[max_val]['seq'])

print(f"Longest in test: {max_test} ({max_test_len} residues)")
print(f"Longest in validation: {max_val} ({max_val_len} residues)")

Longest in test: 1ka2.A (499 residues)
Longest in validation: 4q65.A (493 residues)
